# Default Game Configuration

[display]
width = 800
height = 600
fullscreen = false
vsync = true
fov = 60

[audio]
master_volume = 1.0
music_volume = 0.7
effects_volume = 0.8
weapon_volume = 0.9

[controls]
mouse_sensitivity = 2.0
invert_mouse = false
movement_speed = 4.0

[graphics]
texture_quality = "high"    # high, medium, low
draw_distance = 20.0
show_fps = true

[gameplay]
difficulty = "normal"       # easy, normal, hard
weapon_bob = true
head_bob = true